// Generated by the protocol buffer compiler.  DO NOT EDIT!
#region Designer generated code

using DotBPE.Protobuf;
using System.Collections.Generic;

namespace DotBPE.Hangfire {
    public static class HttpApiRouterOptions {


        static Dictionary<string, List<HttpApiOption>> routeDict = new Dictionary<string, List<HttpApiOption>>();
        static HttpApiRouterOptions()
        { 
            AddRouter("",new HttpApiOption()
            {
                ServiceId = 2000,
                MessageId = 100,
                Path = "/api/hangfire/excute",
                Method = "post",
                Description ="执行任务，由调度程序调度",
                Timeout = 0,
                Plugin = ""
            });
            AddRouter("",new HttpApiOption()
            {
                ServiceId = 2001,
                MessageId = 101,
                Path = "/api/hangfire/enqueue",
                Method = "post",
                Description ="队列任务",
                Timeout = 0,
                Plugin = ""
            });
            AddRouter("",new HttpApiOption()
            {
                ServiceId = 2001,
                MessageId = 102,
                Path = "/api/hangfire/schedule",
                Method = "post",
                Description ="延迟任务，延迟单位分钟",
                Timeout = 0,
                Plugin = ""
            });
            AddRouter("",new HttpApiOption()
            {
                ServiceId = 2001,
                MessageId = 103,
                Path = "/api/hangfire/schedulesecond",
                Method = "post",
                Description ="延迟任务，延迟单位分钟",
                Timeout = 0,
                Plugin = ""
            });
            AddRouter("",new HttpApiOption()
            {
                ServiceId = 2001,
                MessageId = 104,
                Path = "/api/hangfire/enqueuetransfor",
                Method = "post",
                Description ="队列任务 转发服务请求异步调用",
                Timeout = 0,
                Plugin = ""
            });
            AddRouter("",new HttpApiOption()
            {
                ServiceId = 2001,
                MessageId = 105,
                Path = "/api/hangfire/scheduletransfor",
                Method = "post",
                Description ="延迟任务，延迟单位分钟  转发服务请求异步调用",
                Timeout = 0,
                Plugin = ""
            });
            AddRouter("",new HttpApiOption()
            {
                ServiceId = 2001,
                MessageId = 106,
                Path = "/api/hangfire/schedulesecondtransfor",
                Method = "post",
                Description ="延迟任务，延迟单位为秒， 转发服务请求异步调用",
                Timeout = 0,
                Plugin = ""
            }); 
        }

        private static void AddRouter(string category, HttpApiOption routerOption)
        {
            category = string.IsNullOrEmpty(category) ? "default" : category;
            if (!routeDict.ContainsKey(category))
            {
                routeDict.Add(category, new List<HttpApiOption>());
            }          
            routeDict[category].Add(routerOption);
        }

        public static List<HttpApiOption> GetList(string category="default")
        {
            if (routeDict.ContainsKey(category))
            {
                return routeDict[category];
            }

            return new List<HttpApiOption>();
        }
    }
}
#endregion
