// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: taskConsumerService_2000.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DotBPE.Hangfire {

  /// <summary>Holder for reflection information generated from taskConsumerService_2000.proto</summary>
  public static partial class TaskConsumerService2000Reflection {

    #region Descriptor
    /// <summary>File descriptor for taskConsumerService_2000.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TaskConsumerService2000Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch50YXNrQ29uc3VtZXJTZXJ2aWNlXzIwMDAucHJvdG8SBmRvdGJwZRoTZG90",
            "YnBlX29wdGlvbi5wcm90bxoRdGFza21lc3NhZ2UucHJvdG8ynwEKE1Rhc2tD",
            "b25zdW1lclNlcnZpY2USgAEKBkV4Y3V0ZRIVLmRvdGJwZS5Db21tb25UYXNr",
            "UmVxGhMuZG90YnBlLlRhc2tWb2lkUmVzIkrQ8xhk2vMYQgoUL2FwaS9oYW5n",
            "ZmlyZS9leGN1dGUSBHBvc3QaJOaJp+ihjOS7u+WKoe+8jOeUseiwg+W6pueo",
            "i+W6j+iwg+W6phoFyPMY0A9CIEgBqgIPRG90QlBFLkhhbmdmaXJl8PMYAfjz",
            "GAHo8xgBUABQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotBPE.Protobuf.DotbpeOptionReflection.Descriptor, global::DotBPE.Hangfire.TaskmessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
