// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: taskProducerService_2001.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DotBPE.Hangfire {

  /// <summary>Holder for reflection information generated from taskProducerService_2001.proto</summary>
  public static partial class TaskProducerService2001Reflection {

    #region Descriptor
    /// <summary>File descriptor for taskProducerService_2001.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TaskProducerService2001Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch50YXNrUHJvZHVjZXJTZXJ2aWNlXzIwMDEucHJvdG8SBmRvdGJwZRoTZG90",
            "YnBlX29wdGlvbi5wcm90bxoRdGFza21lc3NhZ2UucHJvdG8yuAcKE1Rhc2tQ",
            "cm9kdWNlclNlcnZpY2USawoHRW5xdWV1ZRIWLmRvdGJwZS5FbnF1ZXVlVGFz",
            "a1JlcRoTLmRvdGJwZS5UYXNrVm9pZFJlcyIz0PMYZdrzGCsKFS9hcGkvaGFu",
            "Z2ZpcmUvZW5xdWV1ZRIEcG9zdBoM6Zif5YiX5Lu75YqhEoMBCghTY2hlZHVs",
            "ZRIXLmRvdGJwZS5TY2hlZHVsZVRhc2tSZXEaEy5kb3RicGUuVGFza1ZvaWRS",
            "ZXMiSdDzGGba8xhBChYvYXBpL2hhbmdmaXJlL3NjaGVkdWxlEgRwb3N0GiHl",
            "u7bov5/ku7vliqHvvIzlu7bov5/ljZXkvY3liIbpkp8SjwEKDlNjaGVkdWxl",
            "U2Vjb25kEhcuZG90YnBlLlNjaGVkdWxlVGFza1JlcRoTLmRvdGJwZS5UYXNr",
            "Vm9pZFJlcyJP0PMYZ9rzGEcKHC9hcGkvaGFuZ2ZpcmUvc2NoZWR1bGVzZWNv",
            "bmQSBHBvc3QaIeW7tui/n+S7u+WKoe+8jOW7tui/n+WNleS9jeWIhumSnxKa",
            "AQoPRW5xdWV1ZVRyYW5zZm9yEhYuZG90YnBlLkVucXVldWVUYXNrUmVxGhMu",
            "ZG90YnBlLlRhc2tWb2lkUmVzIlrQ8xho2vMYUgodL2FwaS9oYW5nZmlyZS9l",
            "bnF1ZXVldHJhbnNmb3ISBHBvc3QaK+mYn+WIl+S7u+WKoSDovazlj5HmnI3l",
            "iqHor7fmsYLlvILmraXosIPnlKgSswEKEFNjaGVkdWxlVHJhbnNmb3ISFy5k",
            "b3RicGUuU2NoZWR1bGVUYXNrUmVxGhMuZG90YnBlLlRhc2tWb2lkUmVzInHQ",
            "8xhp2vMYaQoeL2FwaS9oYW5nZmlyZS9zY2hlZHVsZXRyYW5zZm9yEgRwb3N0",
            "GkHlu7bov5/ku7vliqHvvIzlu7bov5/ljZXkvY3liIbpkp8gIOi9rOWPkeac",
            "jeWKoeivt+axguW8guatpeiwg+eUqBLBAQoWU2NoZWR1bGVTZWNvbmRUcmFu",
            "c2ZvchIXLmRvdGJwZS5TY2hlZHVsZVRhc2tSZXEaEy5kb3RicGUuVGFza1Zv",
            "aWRSZXMiedDzGGra8xhxCiQvYXBpL2hhbmdmaXJlL3NjaGVkdWxlc2Vjb25k",
            "dHJhbnNmb3ISBHBvc3QaQ+W7tui/n+S7u+WKoe+8jOW7tui/n+WNleS9jeS4",
            "uuenku+8jCDovazlj5HmnI3liqHor7fmsYLlvILmraXosIPnlKgaBcjzGNEP",
            "QiBIAaoCD0RvdEJQRS5IYW5nZmlyZfDzGAH48xgB6PMYAVAAUAFiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotBPE.Protobuf.DotbpeOptionReflection.Descriptor, global::DotBPE.Hangfire.TaskmessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
