// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: taskConsumerService_2000.proto
#region Designer generated code

using System;
using System.Threading.Tasks;
using DotBPE.Rpc;
using DotBPE.Protocol.Amp;
using DotBPE.Rpc.Exceptions;
using Google.Protobuf;
using DotBPE.Rpc.Client;

namespace DotBPE.Hangfire {

    //start for class TaskConsumerServiceClient
    public sealed class TaskConsumerServiceClient : AmpInvokeClient
    {
        public TaskConsumerServiceClient(ICallInvoker<AmpMessage> callInvoker) : base(callInvoker)
        {

        }

        //同步方法
        public RpcResult<TaskVoidRes> Excute(CommonTaskReq req)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(2000, 100);

            message.FriendlyServiceName = "TaskConsumerService.Excute";


            message.Data = req.ToByteArray();
            var response = base.CallInvoker.BlockingCall(message);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
            var result = new RpcResult<TaskVoidRes>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            
            if (response.Data == null)
            {
                result.Data  =  new TaskVoidRes();
            }
            else
            {
                result.Data = TaskVoidRes.Parser.ParseFrom(response.Data);
            }

            return result;
        }

        public async Task<RpcResult<TaskVoidRes>> ExcuteAsync(CommonTaskReq req, int timeOut = 3000)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(2000, 100);
            message.FriendlyServiceName = "TaskConsumerService.Excute";
            message.Data = req.ToByteArray();
            var response = await base.CallInvoker.AsyncCall(message, timeOut);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
           var result = new RpcResult<TaskVoidRes>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            
            if (response.Data == null)
            {
                result.Data = new TaskVoidRes();
            }
            else
            {
                result.Data = TaskVoidRes.Parser.ParseFrom(response.Data);
            }

            return result;
        }

    }
    //end for class TaskConsumerServiceClient
}
#endregion