// Generated by the protocol buffer compiler.  DO NOT EDIT!
#region Designer generated code

using DotBPE.Protobuf;
using System.Collections.Generic;

namespace Hangfire.Consumer {
    public static class HttpApiRouterOptions {
        public static List<HttpApiOption> GetList()
        {
            var list = new List<HttpApiOption>();

            list.Add(new HttpApiOption()
            {
                ServiceId = 2000,
                MessageId = 1,
                Path = "/api/task/excute",
                Method = "post",
                Description ="队列任务",
                Timeout = 0,
                Plugin = ""
            });
 return list;
        }
    }
}
#endregion
