// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: taskproducer_1000.proto

#region Designer generated code

using DotBPE.Protocol.Amp;
using DotBPE.Rpc;
using Google.Protobuf;
using System.Threading.Tasks;

namespace Hangfire.Producer
{
    //start for class AbstractTaskProducerService
    public abstract class TaskProducerServiceBase : ServiceActor
    {
        protected override int ServiceId => 1000;


        public override Task<AmpMessage> ProcessAsync(AmpMessage req)
        {
            switch (req.MessageId)
            {

                //方法 TaskProducerService.Enqueue
                case 1: return this.ProcessEnqueueAsync(req);

                //方法 TaskProducerService.Schedule
                case 2: return this.ProcessScheduleAsync(req);

                //方法 TaskProducerService.ScheduleSecond
                case 3: return this.ProcessScheduleSecondAsync(req);

                default: return base.ProcessNotFoundAsync(req);
            }
        }



        //调用委托
        private async Task<AmpMessage> ProcessEnqueueAsync(AmpMessage req)
        {
            EnqueueReq request = null;

            if (req.Data == null)
            {
                request = new EnqueueReq();
            }
            else
            {
                request = EnqueueReq.Parser.ParseFrom(req.Data);
            }

            req.FriendlyServiceName = "TaskProducerService.Enqueue";

            var result = await EnqueueAsync(request);
            var response = AmpMessage.CreateResponseMessage(req.ServiceId, req.MessageId);

            response.FriendlyServiceName = "TaskProducerService.Enqueue";
            response.Code = result.Code;
            if (result.Data != null)
            {
                response.Data = result.Data.ToByteArray();
            }
            return response;
        }
        //抽象方法
        public abstract Task<RpcResult<VoidRes>> EnqueueAsync( EnqueueReq req);

        //调用委托
        private async Task<AmpMessage> ProcessScheduleAsync(AmpMessage req)
        {
            ScheduleReq request = null;

            if (req.Data == null)
            {
                request = new ScheduleReq();
            }
            else
            {
                request = ScheduleReq.Parser.ParseFrom(req.Data);
            }

            req.FriendlyServiceName = "TaskProducerService.Schedule";

            var result = await ScheduleAsync(request);
            var response = AmpMessage.CreateResponseMessage(req.ServiceId, req.MessageId);

            response.FriendlyServiceName = "TaskProducerService.Schedule";
            response.Code = result.Code;
            if (result.Data != null)
            {
                response.Data = result.Data.ToByteArray();
            }
            return response;
        }
        //抽象方法
        public abstract Task<RpcResult<VoidRes>> ScheduleAsync( ScheduleReq req);

        //调用委托
        private async Task<AmpMessage> ProcessScheduleSecondAsync(AmpMessage req)
        {
            ScheduleReq request = null;

            if (req.Data == null)
            {
                request = new ScheduleReq();
            }
            else
            {
                request = ScheduleReq.Parser.ParseFrom(req.Data);
            }

            req.FriendlyServiceName = "TaskProducerService.ScheduleSecond";

            var result = await ScheduleSecondAsync(request);
            var response = AmpMessage.CreateResponseMessage(req.ServiceId, req.MessageId);

            response.FriendlyServiceName = "TaskProducerService.ScheduleSecond";
            response.Code = result.Code;
            if (result.Data != null)
            {
                response.Data = result.Data.ToByteArray();
            }
            return response;
        }
        //抽象方法
        public abstract Task<RpcResult<VoidRes>> ScheduleSecondAsync( ScheduleReq req);

    }

    //end for class AbstractTaskProducerService
}

#endregion Designer generated code