// Generated by the protocol buffer compiler.  DO NOT EDIT!
#region Designer generated code

using DotBPE.Protobuf;
using System.Collections.Generic;

namespace Hangfire.Producer {
    public static class HttpApiRouterOptions {
        public static List<HttpApiOption> GetList()
        {
            var list = new List<HttpApiOption>();

            list.Add(new HttpApiOption()
            {
                ServiceId = 1000,
                MessageId = 1,
                Path = "/api/task/enqueue",
                Method = "all",
                Description ="队列任务",
                Timeout = 0,
                Plugin = ""
            });

            list.Add(new HttpApiOption()
            {
                ServiceId = 1000,
                MessageId = 2,
                Path = "/api/task/schedule",
                Method = "all",
                Description ="延迟任务，延迟单位分钟",
                Timeout = 0,
                Plugin = ""
            });

            list.Add(new HttpApiOption()
            {
                ServiceId = 1000,
                MessageId = 3,
                Path = "/api/task/schedule/second",
                Method = "all",
                Description ="延迟任务，延迟单位为秒，其实是不准的",
                Timeout = 0,
                Plugin = ""
            });
 return list;
        }
    }
}
#endregion
