// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: taskproducer_1000.proto
#region Designer generated code

using System;
using System.Threading.Tasks;
using DotBPE.Rpc;
using DotBPE.Protocol.Amp;
using DotBPE.Rpc.Exceptions;
using Google.Protobuf;
using DotBPE.Rpc.Client;

namespace Hangfire.Producer {

    //start for class TaskProducerServiceClient
    public sealed class TaskProducerServiceClient : AmpInvokeClient
    {
        public TaskProducerServiceClient(ICallInvoker<AmpMessage> callInvoker) : base(callInvoker)
        {

        }

        //同步方法
        public RpcResult<VoidRes> Enqueue(EnqueueReq req)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(1000, 1);

            message.FriendlyServiceName = "TaskProducerService.Enqueue";


            message.Data = req.ToByteArray();
            var response = base.CallInvoker.BlockingCall(message);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
            var result = new RpcResult<VoidRes>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = VoidRes.Parser.ParseFrom(response.Data);
            }
            return result;
        }

        public async Task<RpcResult<VoidRes>> EnqueueAsync(EnqueueReq req, int timeOut = 3000)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(1000, 1);
            message.FriendlyServiceName = "TaskProducerService.Enqueue";
            message.Data = req.ToByteArray();
            var response = await base.CallInvoker.AsyncCall(message, timeOut);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
           var result = new RpcResult<VoidRes>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = VoidRes.Parser.ParseFrom(response.Data);
            }

            return result;
        }

        //同步方法
        public RpcResult<VoidRes> Schedule(ScheduleReq req)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(1000, 2);

            message.FriendlyServiceName = "TaskProducerService.Schedule";


            message.Data = req.ToByteArray();
            var response = base.CallInvoker.BlockingCall(message);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
            var result = new RpcResult<VoidRes>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = VoidRes.Parser.ParseFrom(response.Data);
            }
            return result;
        }

        public async Task<RpcResult<VoidRes>> ScheduleAsync(ScheduleReq req, int timeOut = 3000)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(1000, 2);
            message.FriendlyServiceName = "TaskProducerService.Schedule";
            message.Data = req.ToByteArray();
            var response = await base.CallInvoker.AsyncCall(message, timeOut);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
           var result = new RpcResult<VoidRes>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = VoidRes.Parser.ParseFrom(response.Data);
            }

            return result;
        }

        //同步方法
        public RpcResult<VoidRes> ScheduleSecond(ScheduleReq req)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(1000, 3);

            message.FriendlyServiceName = "TaskProducerService.ScheduleSecond";


            message.Data = req.ToByteArray();
            var response = base.CallInvoker.BlockingCall(message);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
            var result = new RpcResult<VoidRes>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = VoidRes.Parser.ParseFrom(response.Data);
            }
            return result;
        }

        public async Task<RpcResult<VoidRes>> ScheduleSecondAsync(ScheduleReq req, int timeOut = 3000)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(1000, 3);
            message.FriendlyServiceName = "TaskProducerService.ScheduleSecond";
            message.Data = req.ToByteArray();
            var response = await base.CallInvoker.AsyncCall(message, timeOut);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
           var result = new RpcResult<VoidRes>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = VoidRes.Parser.ParseFrom(response.Data);
            }

            return result;
        }

    }
    //end for class TaskProducerServiceClient
}
#endregion